<div class="row">

    <hgroup class="col-sm-12 col-md-12 col-lg-12">

        <h1>Product suggestie toevoegen</h1>

    </hgroup>

</div>

<?php
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data',
    'action' => $this->url('groceryProduct', array('action' => 'add'))
));
?>

<?php echo $this->form()->openTag($form); ?>

<div class="row">

    <div class="col-sm-12 col-md-12 col-lg-12">

        <div class="form-group">

            <div class="col-sm-12 col-md-12 col-lg-12">

                <button type="submit" id="submit" class="btn btn-info">Opslaan</button> <a href="<?php echo $this->url('groceryProduct', array('action' => 'productSuggestions')); ?>" class="btn btn-default" title="Annuleren">Annuleren</a>

            </div>

        </div>

        <h2><?php echo $this->translate('General information'); ?></h2>
        <div class="form-group">

            <?php echo $this->formLabel($form->get('productNumber')); ?>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo $this->formText($form->get('productNumber')); ?>

            </div>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo (count($form->getMessages('name')) > 0 ? $form->getMessages('name')['isEmpty'] : '&nbsp;' ) ?>

            </div>

        </div>

        <div class="form-group">

            <?php echo $this->formLabel($form->get('name')); ?>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo $this->formText($form->get('name')); ?>

            </div>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo (count($form->getMessages('name')) > 0 ? $form->getMessages('name')['isEmpty'] : '&nbsp;' ) ?>

            </div>

        </div>

        <div class="form-group">

            <?php echo $this->formLabel($form->get('description')); ?>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo $this->formTextarea($form->get('description')); ?>

            </div>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo (count($form->getMessages('name')) > 0 ? $form->getMessages('name')['isEmpty'] : '&nbsp;' ) ?>

            </div>

        </div>

        <div class="form-group">

            <?php echo $this->formLabel($form->get('price')); ?>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <span class="currencyinput"><span class="currency">&euro;</span><?php echo $this->formNumber($form->get('price')); ?></span>

            </div>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo (count($form->getMessages('price')) > 0 ? $form->getMessages('price')['isEmpty'] : '&nbsp;' ) ?>

            </div>

        </div>
        <div class="form-group">

            <?php echo $this->formLabel($form->get('orderFrequenty')); ?>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo $this->formSelect($form->get('orderFrequenty')); ?>

            </div>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo (count($form->getMessages('orderFrequenty')) > 0 ? $form->getMessages('orderFrequenty')['isEmpty'] : '&nbsp;' ) ?>

            </div>

        </div>
        <hr>
        <h2><?php echo $this->translate('Images'); ?></h2>
        <div class="form-group">

            <?php echo $this->formLabel($form->get('productImage')); ?>

            <div class="col-sm-4 col-md-4 col-lg-4">
                <input type="text" name="externalURLfield" value="<?php echo $productImageURL; ?>" id="externalURLfield" class="form-control" />
            </div>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo (count($form->getMessages('productImage')) > 0 ? $form->getMessages('productImage')['isEmpty'] : '&nbsp;' ) ?>

            </div>

        </div>

        <div class="form-group">

            <?php echo $this->formLabel($formProductImage->get('nameImage')); ?>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo $this->formText($formProductImage->get('nameImage')); ?>

            </div>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo (count($formProductImage->getMessages('nameImage')) > 0 ? $formProductImage->getMessages('nameImage')['isEmpty'] : '&nbsp;' ) ?>

            </div>

        </div>

        <div class="form-group">

            <?php echo $this->formLabel($formProductImage->get('alt')); ?>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo $this->formText($formProductImage->get('alt')); ?>

            </div>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo (count($formProductImage->getMessages('alt')) > 0 ? $formProductImage->getMessages('alt')['isEmpty'] : '&nbsp;' ) ?>

            </div>

        </div>

        <div class="form-group">

            <?php echo $this->formLabel($formProductImage->get('descriptionImage')); ?>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo $this->formText($formProductImage->get('descriptionImage')); ?>

            </div>

            <div class="col-sm-4 col-md-4 col-lg-4">

                <?php echo (count($formProductImage->getMessages('descriptionImage')) > 0 ? $formProductImage->getMessages('descriptionImage')['isEmpty'] : '&nbsp;' ) ?>

            </div>

        </div>

        <hr>
        <h2><?php echo $this->translate('Product groups'); ?></h2>
        <div class="form-group">
            <div class="col-sm-12 col-md-12 col-lg-12">

                <?php echo $this->formMultiCheckbox($form->get('productGroups')); ?>

            </div>

            <div class="col-sm-12 col-md-12 col-lg-12">

                <?php echo (count($form->getMessages('productGroups')) > 0 ? $form->getMessages('productGroups')['isEmpty'] : '&nbsp;' ) ?>

            </div>

        </div>
        <hr>

        <br/><br/>

        <div class="form-group">

            <div class="col-sm-12 col-md-12 col-lg-12">

                <button type="submit" id="submit" class="btn btn-info">Opslaan</button> <a href="<?php echo $this->url('groceryProduct', array('action' => 'productSuggestions')); ?>" class="btn btn-default" title="Annuleren">Annuleren</a>

            </div>

        </div>

    </div>

</div>
<?php echo $this->form()->closeTag($form); ?>
<script>

    $(document).ready(function () {
        tinymce.init({selector: 'textarea'});
    });

</script>