<div class="row">

    <hgroup class="col-sm-12 col-md-12 col-lg-12">

        <h1>Producten</h1>

    </hgroup>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">

        <a href="<?php echo $this->url('groceryProduct', array('action' => 'add')); ?>" class="btn btn-default" title="product toevoegen">Voeg product toe</a><br/><br/>

    </div>
</div>
<form class="form-inline" method="post" action="<?php echo $this->url('groceryProduct', array('action' => 'index')); ?>">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="form-group has-default has-feedback">
                <div class="input-group">
                    <span class="input-group-addon"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></span>
                    <input type="text" name="searchString" class="form-control" value="<?php echo $searchTerm; ?>" placeholder="Zoeken..." id="search"> 
                </div>
            </div>
        </div>
    </div>
    <br/>
    <?php if (count($productGroupsForSelect) > 0) { ?>
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <span class="selectAllProductgGroups btn btn-primary">Selecteer alles</span>
                <span class="deSelectAllProductgGroups btn btn-primary">Deselecteer alles</span>
                <br/><br/>
            </div>
        </div>

        <div class="row" id="searchProductGroups">
            <?php foreach ($productGroupsForSelect AS $index => $productGroup) { ?>
                <div class="col-sm-4 col-md-4 col-lg-4">
                    <input type="checkbox" <?php echo (in_array($productGroup->getId(), $productGroups) ? 'checked="checked"' : ''); ?> value="<?php echo $productGroup->getId(); ?>" name="productGroups[]" id="checkbox<?php echo $index; ?>"/>
                    <label for="checkbox<?php echo $index; ?>"><?php echo $productGroup->getName(); ?></label>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="form-group">
                <br/>
                <input type="submit" name="zoeken" value="Zoeken" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <?php
        if (count($products) > 0) {
            ?>
            <?php
            echo $this->paginationControl($products, 'Sliding', 'partial/paginator');
            ?>
            <table class="table table-striped table-bordered" id="productTable">
                <tr>
                    <th width="75">&nbsp;</th>
                    <th>Naam</th>
                    <th>Prijs</th>
                    <th class="text-center"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
                </tr>
                <?php
                foreach ($products AS $product) {
                    $imageUrl = '';
                    ?>
                    <?php $images = $product->getProductImages(); ?>
                    <?php
                    foreach ($images AS $image) {
                        if (!empty($image->getProductImageTypes('75x75'))) {
                            foreach ($image->getProductImageTypes('75x75') AS $imageType) {
                                $imageUrl = '<img class="img-responsive" src="/' . $imageType->getFolder() . $imageType->getFileName() . '" alt="' . $product->getName() . '" width="75" height="auto" />';
                            }
                        }
                        break;
                    }
                    ?>
                    <tr>
                        <td><?php echo $imageUrl; ?></td>
                        <td><?php echo $product->getName(); ?></td>
                        <td>&euro; <?php echo ($product->getPrice() ? number_format($product->getPrice(), 2, ',', ' ') : '0'); ?></td>
                        <td class="text-center">
                            <a href="<?php echo $this->url('groceryProduct', array('action' => 'detail', 'id' => $product->getProductId())); ?>" class="btn btn-default" title="product bekijken"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a>
                            <a href="<?php echo $this->url('groceryProduct', array('action' => 'change', 'id' => $product->getProductId())); ?>" class="btn btn-default" title="product wijzigen"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                            <a href="<?php echo $this->url('groceryProduct', array('action' => 'delete', 'id' => $product->getProductId())); ?>" class="btn btn-default" title="product verwijderen"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </table>
            <?php
            echo $this->paginationControl($products, 'Sliding', 'partial/paginator');
            ?>
            <?php
        } else {
            ?>
            <p><br/>Geen producten gevonden.</p>
            <?php
        }
        ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <a href="<?php echo $this->url('groceryProduct', array('action' => 'add')); ?>" class="btn btn-default" title="product toevoegen">Voeg product toe</a>
    </div>
</div>