<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h3><?php echo $this->translate('Product suggesties'); ?></h3>
        <table class="table table-striped table-bordered" id="productTable">
            <tr>
                <th width="75">&nbsp;</th>
                <th>Product naam</th>
                <th>Link</th>
                <th class="text-center"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
            </tr>
            <?php if (count($productSuggestions) > 0) { ?>
                <?php foreach ($productSuggestions AS $index => $productSuggestion) { ?>
                    <tr>
                        <td><?php echo $index + 1; ?></td>
                        <td><?php echo $productSuggestion->getProductName(); ?></td>
                        <td><?php echo $productSuggestion->getLink(); ?></td>
                        <td class="text-center">
                            <a href="<?php echo $this->url('groceryProduct', array('action' => 'addDeclineProductSuggestion', 'id' => $productSuggestion->getId(), 'approve' => 1)); ?>" class="btn btn-success" title="Add"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                            <a href="<?php echo $this->url('groceryProduct', array('action' => 'addDeclineProductSuggestion', 'id' => $productSuggestion->getId(), 'approve' => 2)); ?>" class="btn btn-warning" title="Decline"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></a>
                            <a href="<?php echo $this->url('groceryProduct', array('action' => 'removeProductSuggestion', 'id' => $productSuggestion->getId())); ?>" class="btn btn-danger" title="Remove"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td class="text-center" colspan="4"><?php echo $this->translate('No product suggestions'); ?></td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h3><?php echo $this->translate('Goedgekeurde product suggesties'); ?></h3>
        <table class="table table-striped table-bordered" id="productTable">
            <tr>
                <th width="75">&nbsp;</th>
                <th>Product naam</th>
                <th>Link</th>
            </tr>
            <?php if (count($productSuggestionsAccepted) > 0) { ?>
                <?php foreach ($productSuggestionsAccepted AS $index => $productSuggestion) { ?>
                    <tr>
                        <td><?php echo $index + 1; ?></td>
                        <td><?php echo $productSuggestion->getProductName(); ?></td>
                        <td><?php echo $productSuggestion->getLink(); ?></td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td class="text-center" colspan="4"><?php echo $this->translate('No approved suggestions'); ?></td>
                </tr>
            <?php } ?>
        </table>

    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">

        <h3><?php echo $this->translate('Afgewezen product suggesties'); ?></h3>
        <table class="table table-striped table-bordered" id="productTable">
            <tr>
                <th width="75">&nbsp;</th>
                <th>Product naam</th>
                <th>Link</th>
                <th class="text-center"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
            </tr>
            <?php if (count($productSuggestionsDeclined) > 0) { ?>
                <?php foreach ($productSuggestionsDeclined AS $index => $productSuggestion) { ?>
                    <tr>
                        <td><?php echo $index + 1; ?></td>
                        <td><?php echo $productSuggestion->getProductName(); ?></td>
                        <td><?php echo $productSuggestion->getLink(); ?></td>
                        <td class="text-center">
                            <a href="<?php echo $this->url('groceryProduct', array('action' => 'removeProductSuggestion', 'id' => $productSuggestion->getId())); ?>" class="btn btn-danger" title="Remove"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td class="text-center" colspan="4"><?php echo $this->translate('No declined suggestions'); ?></td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>