<div class="row">
    <hgroup class="col-sm-12 col-md-12 col-lg-12">
        <h1><?php echo $this->translate('Product groups'); ?></h1>
    </hgroup>
    <div class="col-sm-12 col-md-12 col-lg-12">
        <a href="<?php echo $this->url('groceryProductGroup', array('action' => 'add')); ?>" class="btn btn-default" title="product groep toevoegen">Voeg product groep toe</a>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-12">
        <?php
        if (!empty($productGroups)) {
            ?>
            <table class="table table-striped table-bordered" id="productTable">
                <tr>
                    <th>Naam</th>
                    <th colspan="2">Aantal producten</th>
                </tr>
                <?php
                foreach ($productGroups AS $productGroup) {
                    ?>
                    <tr>
                        <td><?php echo $productGroup->getName(); ?></td>
                        <td><?php echo count($productGroup->getProducts()); ?></td>
                        <td class="text-center">
                            <a href="<?php echo $this->url('groceryProductGroup', array('action' => 'change', 'id' => $productGroup->getId())); ?>" class="btn btn-default" title="product groep wijzigen"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                            <a href="<?php echo $this->url('groceryProductGroup', array('action' => 'delete', 'id' => $productGroup->getId())); ?>" class="btn btn-default" title="product groep verwijderen"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                            <a href="<?php echo $this->url('groceryProductGroup', array('action' => 'detail', 'id' => $productGroup->getId())); ?>" class="btn btn-default" title="product groep bekijken"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </table>
            <?php
        } else {
            ?>
            <p>Nog geen product groepen.</p>
            <?php
        }
        ?>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-12">
        <a href="<?php echo $this->url('groceryProductGroup', array('action' => 'add')); ?>" class="btn btn-default" title="product groep toevoegen">Voeg product groep toe</a>
    </div>
</div>