<script>
    $(document).ready(function () {
        $('body').keypress(function (event) {

            if (event.keyCode === 10 || event.keyCode === 13)
                event.preventDefault();

        });

    });
</script>


<div class="row">
    <hgroup class="col-sm-12 col-md-12 col-lg-12">
        <h1><?php echo $this->translate('Product list detail of weeknumber'); ?>: <?php echo $productList->getWeeknumber(); ?></h1>
    </hgroup>
    <hgroup class="col-sm-12 col-md-12 col-lg-12">
        <h2><?php echo $this->translate('Products'); ?></h2>
    </hgroup>
    <div class="col-sm-8 col-md-8 col-lg-8" style="padding-top:10px;">
        <?php
        ?>
        <table class="table table-striped table-bordered" id="productTable">
            <tr>
                <th width="75">&nbsp;</th>
                <th>Naam</th>
                <th class="text-center" colspan="2">Aantal</th>

                <th class="text-center"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></th>
            </tr>
            <tbody id="bodyProductList">
                <?php
                foreach ($productList->getProductListDetails() AS $product) {
                    if ($product->getDeleted() == true) {
                        continue;
                    }
                    $image = '';
                    ?>
                    <?php $images = $product->getProduct()->getProductImages(); ?>
                    <?php
                    foreach ($images AS $image) {
                        foreach ($image->getProductImageTypes('150x150') AS $imageType) {
                            $image = '<img class="img-responsive" src="/' . $imageType->getFolder() . $imageType->getFileName() . '" alt="' . $product->getProduct()->getName() . '" width="75" height="auto" />';
                        }
                        break;
                    }
                    ?>

                    <tr id="productListDetail<?php echo $product->getId(); ?>" data-productlistdetailid="<?php echo $product->getId(); ?>">
                        <td><?php echo $image; ?></td>
                        <td><?php echo $product->getProduct()->getName(); ?></td>
                        <td class="text-center" id="productQuantity<?php echo $product->getProduct()->getProductId(); ?>"><?php echo $product->getQuantity(); ?></td>
                        <td class="text-center">
                            <span class="glyphicon glyphicon-circle-arrow-up addProduct" data-modus="add" data-productlistdetailid="<?php echo $product->getId(); ?>" data-link="<?php echo $this->serverUrl($this->url('groceryProductListAjax', array('action' => 'addRemoveProduct'))); ?>" aria-hidden="true"></span>
                            <span class="glyphicon glyphicon-circle-arrow-down removeProduct" data-modus="remove" data-productlistdetailid="<?php echo $product->getId(); ?>" data-link="<?php echo $this->serverUrl($this->url('groceryProductListAjax', array('action' => 'addRemoveProduct'))); ?>" aria-hidden="true"></span>
                        </td>
                        <td class="text-center">
                            <a href="<?php echo $this->url('groceryProduct', array('action' => 'detail', 'id' => $product->getProduct()->getProductId())); ?>" class="btn btn-default" title="product bekijken"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a>
                            <a href="" data-link="<?php echo $this->serverUrl($this->url('groceryProductListAjax', array('action' => 'removeProduct'))); ?>" class="btn btn-default deleteProduct" title="product verwijderen van product lijst"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                    <tr>
                        <td colspan="5" id="noProductsOnList" <?php echo (count($productList->getProductListDetails()) == 0 ? '' : 'style="display:none;"') ?>>Geen producten op deze lijst.</td>
                    <tr>
            </tbody>
        </table>
        
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php if ($productList->getYear() == $year && $productList->getWeeknumber() > $weekNumber) { ?>
            <h4 style="margin-top:0;">Zoek naar producten</h4>
            <form class="form-inline">
                <div class="form-group has-success has-feedback">
                    <div class="input-group">
                        <span class="input-group-addon"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></span>
                        <input type="text" class="form-control" value="" placeholder="Zoeken..." id="search">
                    </div>
                </div>
                <input type="hidden" name="productListID" id="productListID" value="<?php echo $productList->getId(); ?>" />
                <input type="hidden" name="ajaxURL" id="ajaxURL" value="<?php echo $this->serverUrl($this->url('groceryProductListAjax', array('action' => 'searchProducts'))); ?>"/>
            </form><br/>
            <p>
                Zit het gewenste product er niet bij? Doe dan een suggestie. Klik op onderstaande knop om product te laten toevoegen aan het assortiment.<br/>
                <button type="button" class="btn btn-primary btn-info" data-toggle="modal" data-target="#suggestionModal">

                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $this->translate('Make a suggestion'); ?>

                </button>
            </p>
            <div id="productsTableSearchResult">
                <table id="productList" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th>Naam</th>
                            <th class="text-center"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></th>
                        </tr>
                    </thead>
                    <tbody id="productlistBody">

                    </tbody>
                </table>
            </div>
            <div id="productsTable">
                <table id="products" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th width="75">&nbsp;</th>
                            <th>Naam</th>
                            <th class="text-center"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></th>
                        <tr>
                    </thead>
                    <tbody id="productsBody">
                        <?php
                        foreach ($products AS $product) {
                            $image = '';
                            ?>
                            <?php $images = $product->getProductImages(); ?>
                            <?php
                            foreach ($images AS $image) {
                                foreach ($image->getProductImageTypes('150x150') AS $imageType) {
                                    $image = '<img class="img-responsive" src="/' . $imageType->getFolder() . $imageType->getFileName() . '" alt="' . $product->getName() . '" width="75" height="auto" />';
                                }
                                break;
                            }
                            ?>
                            <tr>
                                <td><?php echo $image; ?></td>
                                <td><?php echo $product->getName() ?></td>
                                <td class="text-center"><span data-ajaxurl="<?php echo $this->serverUrl($this->url('groceryProductListAjax', array('action' => 'addProductToProductList'))); ?>" data-productlistid="<?php echo $productList->getId(); ?>" data-productid="<?php echo $product->getProductId(); ?>"  class="glyphicon glyphicon-plus addProductToList" aria-hidden="true"></span></td>
                            <tr>
                                <?php
                            }
                            ?>
                    </tbody>
                </table>
            </div>
        <?php } ?>
    </div>
</div>
<?php
 echo $this->partial('partial/suggestion');
?>

