<div class="row">
    <hgroup class="col-sm-12 col-md-12 col-lg-12">
        <h1>Product weetjes</h1>
    </hgroup>
    <div class="col-sm-12 col-md-12 col-lg-12">
        <a href="<?php echo $this->url('groceryProductFact', array('action' => 'add')); ?>" class="btn btn-default" title="product weetje toevoegen">Voeg product weetje toe</a>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-12">
        <?php
        if (!empty($productFacts)) {
            ?>
            <table class="table table-striped table-bordered" id="productTable">
                <tr>
                    <th>Naam</th>
                    <th colspan="2">Gekoppeld aan product</th>
                </tr>
                <?php
                foreach ($productFacts AS $productFact) {
                    ?>
                    <tr>
                        <td><?php echo $productFact->getProductFactTitle(); ?></td>
                        <td><?php echo $productFact->getProduct()->getName(); ?></td>
                        <td class="text-center">
                            <a href="<?php echo $this->url('groceryProductFact', array('action' => 'change', 'id' => $productFact->getProductFactId())); ?>" class="btn btn-default" title="product fact wijzigen"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                            <a href="<?php echo $this->url('groceryProductFact', array('action' => 'delete', 'id' => $productFact->getProductFactId())); ?>" class="btn btn-default" title="product fact verwijderen"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </table>
            <?php
        } else {
            ?>
        <p><br/>Nog geen product weetjes.</p>
            <?php
        }
        ?>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-12">
        <a href="<?php echo $this->url('groceryProductFact', array('action' => 'add')); ?>" class="btn btn-default" title="product weetje toevoegen">Voeg product weetje toe</a>
    </div>
</div>