<?php if ($this->pageCount): ?>
    <ul class="pagination pagination-sm">
        <li class="disabled">
            <a>
                <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
                <?php echo $this->translate('of');?>
                <?php echo $this->totalItemCount; ?> 
                <?php echo $this->translate('items');?>
            </a>
        </li>
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li>
                <a href="<?php echo $this->url($this->route, array(), false, true); ?>?page=<?php echo $this->previous; ?>&popup=true">
                    <<
                </a>
            </li>
        <?php else: ?>
            <li class="disabled">
                <a href="#">
                    <<
                </a>
            </li>
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array(), false, true); ?>?page=<?php echo $page; ?>&popup=true">
                        <?php echo $page; ?>
                    </a>
                </li>
            <?php else: ?>
                <li class="active">
                    <a href="#"><?php echo $page; ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li>
                <a href="<?php echo $this->url($this->route, array(), false, true); ?>?page=<?php echo $this->next; ?>&popup=true">
                    >>
                </a>
            </li>
        <?php else: ?>
            <li class="disabled">
                <a href="#">
                    >>
                </a>
            </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>