<div class="row">
    <div class="col-md-12">
        <?php
        if (!empty($productLists)) {
            foreach ($years AS $year) {
                ?>
                <h2><?php echo $year['year']; ?></h2>
                <table class="table table-striped table-bordered" id="productTable">
                    <tr>
                        <th>Weeknummer</th>
                        <th>Totaal budget</th>
                        <th>Aantal producten</th>
                        <th>Totaal prijs</th>
                        <th class="text-center"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
                    </tr>
                    <?php
                    foreach ($productLists AS $productList) {
                        if ($productList->getYear() == $year['year']) {
                            $gendateBeginWeek = new DateTime();
                            $gendateBeginWeek->setISODate($year['year'], $productList->getWeeknumber(), 1); //year , week num , day
                            $gendateEndWeek = new DateTime();
                            $gendateEndWeek->setISODate($year['year'], $productList->getWeeknumber(), 7); //year , week num , day
                            ?>
                            <tr>
                                <td><?php echo $productList->getWeeknumber() . ' (' . $gendateBeginWeek->format('d-m-Y') . ' / ' . $gendateEndWeek->format('d-m-Y') . ')'; ?></td>
                                <td>&euro; <?php echo $totalbudget; ?></td>
                                <td><?php echo count($productList->getUndeletedProductListDetails()); ?></td>
                                <td>&euro; <?php echo $productList->getTotalCost(); ?></td>
                                <td class="text-center">
                                    <a href="<?php echo $this->url('groceryProductList', array('action' => 'detail', 'id' => $productList->getId())); ?>" class="btn btn-default" title="boodschappen lijst bekijken"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a>
                                </td>
                                <?php
                            }
                        }
                        ?>
                </table>
                <?php
            }
        } else {
            ?>
            <p><br/>Nog geen producten.</p>
            <?php
        }
        ?>
    </div>
</div>